// #define FLOW_TAP_TERM 80
// #define CHORDAL_HOLD
// #undef TAPPING_TERM
// #define TAPPING_TERM 300
// #define QUICK_TAP_TERM 120

// #define PERMISSIVE_HOLD
// #define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
// #define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

#define COMBO_TERM 30

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 300000

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 1

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 3

#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "rd6q7/3vwNBA"
#define LAYER_STATE_16BIT
#define COMBO_COUNT 5

// #define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60
#define MAX_DEFERRED_EXECUTORS 10

#define SMTD_GLOBAL_TAP_TERM 200
#define SMTD_GLOBAL_RELEASE_TERM 15
#define SMTD_GLOBAL_FOLLOWING_TAP_TERM 400
#define SMTD_GLOBAL_SEQUENCE_TERM 120
