#define FLOW_TAP_TERM 80
#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 300

#define COMBO_TERM 25

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 300000

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 1

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 3

#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "rd6q7/lbjaOe"
#define LAYER_STATE_16BIT
#define COMBO_COUNT 15

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

