#define FLOW_TAP_TERM 80
#define CHORDAL_HOLD
#undef TAPPING_TERM
#define TAPPING_TERM 300
#define QUICK_TAP_TERM 120

#define PERMISSIVE_HOLD_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

#define COMBO_TERM 30

#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 300000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "rd6q7/x96lEx"
#define LAYER_STATE_16BIT
#define COMBO_COUNT 5

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60
